apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 436713110806.dkr.ecr.us-east-1.amazonaws.com/my-mysql-repo:v0.1
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: clo835ass2
    ports:
    - containerPort: 3306
      protocol: TCP

